lostNoticeProject/urls.py
from django.conf.urls import url

from lostnotice import views

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    # LFList = LostFindList
    # lPage = page of Lost Notice list
    # fPage = page of Find Owner list
    url(r'^LFList/(?P<lPage>[0-9]+)/(?P<fPage>[0-9]+)/$', views.home_page, name='home'),

    #lost notice
    url(r'^(?P<user_id>[0-9]+)/add_new_lost_notice/$', views.add_new_lost_item, name='add_new_lost_item'),
    url(r'^save_new_item_lost/$', views.save_new_item_lost, name='save_new_item_lost'),
    url(r'^lost_notice/(?P<id>[0-9]+)/$', views.detail_lost_item, name='detail_lost_item'),
    #found owner
    url(r'^(?P<user_id>[0-9]+)/add_new_found_owner/$', views.add_new_found_owner, name='add_new_found_owner'),
    url(r'^save_new_found_owner/$', views.save_new_found_owner, name='save_new_found_owner'),
    url(r'^found_owner/(?P<id>[0-9]+)/$', views.detail_found_owner, name='detail_found_owner'),

    #register
    url(r'^register_page/$', views.register_page, name='register_page'),
    url(r'^register_complete/$', views.register_complete, name='register_check'),

    #login
    url(r'^login_page/$', views.login_page, name='login_page'),
    url(r'^login_check/$', views.login_check, name='login_check'),
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    #About
    url(r'^about/$', views.about, name='about'),
]

lostnotice/models.py
from django.db import models

# Create your models here.
class LostNoticeList(models.Model):
	title = models.CharField(max_length=200)
	name_item = models.CharField(max_length=200)
	time_lost = models.CharField(max_length=200)
	location_lost = models.CharField(max_length=200)
	detail = models.CharField(max_length=1000)
	your_name = models.CharField(max_length=200)
	your_email = models.CharField(max_length=200)
	found_it = models.BooleanField(default=False)
	time_submit = models.DateTimeField(null=True, blank=True)

class FindOwnerList(models.Model):
    title = models.CharField(max_length=200)
    name_item = models.CharField(max_length=200)
    time_found = models.CharField(max_length=200)
    location_found = models.CharField(max_length=200)
    detail = models.CharField(max_length=1000)
    your_name = models.CharField(max_length=200)
    your_email = models.CharField(max_length=200)
    found_owner = models.BooleanField(default=False)
    time_submit = models.DateTimeField(null=True, blank=True)

class userData(models.Model):
	username = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	password = models.CharField(max_length=100)
	time_register = models.DateTimeField(null=True, blank=True)

lostnotice/views.py
from django.shortcuts import render
from django.utils import timezone
from django.urls import reverse
from django.http import HttpResponseRedirect

from .models import LostNoticeList, FindOwnerList, userData


def home_page(request, lPage = 1, fPage = 1):
	lPage=int(lPage)
	fPage=int(fPage)
	N = 2
	lost_noitce_list = LostNoticeList.objects.order_by('-time_submit')[(int(lPage)-1)*N:int(lPage)*N]
	found_owner_list = FindOwnerList.objects.order_by('-time_found')[(int(fPage)-1)*N:int(fPage)*N]
	

	if LostNoticeList.objects.filter(id=1):
		lost_notice_lastest = LostNoticeList.objects.order_by('-id')[0]
		lost_last_page = int((lost_notice_lastest.id-1)/N+1)
	else:
		lost_last_page = 1

	if FindOwnerList.objects.filter(id=1):
		found_owner_lastest = FindOwnerList.objects.order_by('-id')[0]
		found_owner_page = int((found_owner_lastest.id-1)/N+1)
	else:
		found_owner_page = 1

		
	valueList = {'lPage'	:  lPage,
				'fPage' 	: fPage,
				'leftLostPage'	: lPage-1,
				'rightLostPage'	: lPage+1,
				'leftFoundPage'	: fPage-1,
				'rightFoundPage': fPage+1,
				'lost_last_page'	: lost_last_page,
				'found_owner_page'	: found_owner_page,
				}

	context = {	'lost_noitce_list' 	: lost_noitce_list,
				'found_owner_list'	: found_owner_list,
				'valueList'			: valueList }
	return render(request, 'homepage.html', context)
########################################################################################
########################################################################################
#Lost Notice
def add_new_lost_item(request, user_id):
	user_data = userData.objects.get(id=user_id)

	context = {	'user_data' : user_data }
	return render(request, 'add_new_lost_item.html', context)
	
def save_new_item_lost(request):
	try:
		title = request.POST['title']
		name_item = request.POST['name_item']
		time_lost = request.POST['time_lost']
		location_lost = request.POST['location_lost']
		detail = request.POST['detail']
		your_name = request.POST['your_name']
		your_email = request.POST['your_email']
	except:
		title = ""
		name_item = ""
		detail = ""
		your_name = ""
		your_email = ""
	else:
		saveData = LostNoticeList(
			title=title,
			name_item=name_item, 
			detail=detail, 
			time_lost=time_lost,
			location_lost=location_lost,
			found_it=False,
			your_name=your_name, 
			your_email=your_email,
			time_submit=timezone.now()
		)
		saveData.save()
		user_data = userData.objects.get(username=your_name)

		context = {	'user_data' : user_data }
		return HttpResponseRedirect(reverse('profile', args=(user_data.id,)))


def detail_lost_item(request, id):
	lost_noitce_list = LostNoticeList.objects.get(id=id)

	context = {	'lost_noitce_list' : lost_noitce_list }
	return render(request, 'detail_lost_item.html', context)

########################################################################################
########################################################################################
#Found owner
def add_new_found_owner(request, user_id):
	user_data = userData.objects.get(id=user_id)

	context = {	'user_data' : user_data }
	return render(request, 'add_new_found_owner.html', context)

def save_new_found_owner(request):
	try:
		title = request.POST['title']
		name_item = request.POST['name_item']
		time_found = request.POST['time_found']
		location_found = request.POST['location_found']
		detail = request.POST['detail']
		your_name = request.POST['your_name']
		your_email = request.POST['your_email']
	except:
		title = ""
		name_item = ""
		detail = ""
		your_name = ""
		your_email = ""
	else:
		saveData = FindOwnerList(
			title=title,
			name_item=name_item, 
			detail=detail, 
			time_found=time_found,
			location_found=location_found,
			found_owner=False,
			your_name=your_name, 
			your_email=your_email,
			time_submit=timezone.now()
		)
		saveData.save()
		user_data = userData.objects.get(username=your_name)

		context = {	'user_data' : user_data }
		return HttpResponseRedirect(reverse('profile', args=(user_data.id,)))

def detail_found_owner(request, id):
	found_owner_list = FindOwnerList.objects.get(id=id)

	context = {	'found_owner_list' : found_owner_list }
	return render(request, 'detail_found_owner.html', context)

########################################################################################
########################################################################################
#register
def register_page(request):
	return render(request, 'register_page.html')

def register_complete(request):
	try:
		username = request.POST['username']
		email = request.POST['email']
		password = request.POST['password']
	except:
		username = " "
	else:
		user_check = userData.objects.filter(username=username)
		if user_check:
			pass
		else:
			saveNewUser = userData(
				username=username, 
				email=email, 
				password = password,
				time_register=timezone.now()
			)
			saveNewUser.save()
		context = {'user_check' : user_check,
					'username'	: username}
		return render(request, 'register_check.html', context)

########################################################################################
########################################################################################
#login
def login_page(request):
	return render(request, 'login_page.html')

#from django.contrib.auth import authenticate, login

def login_check(request):	
	try:
		username = request.POST['username']
		password = request.POST['password']
	except:
		username = ""
	else:
		showH1 = ""
		user_check = userData.objects.filter(username=username)
		if user_check:
			if password == user_check[0].password:
				user_data = userData.objects.get(username=username)
				return HttpResponseRedirect(reverse('profile', args=(user_data.id,)))
			else:
				showH1 = "User : "+user_check[0].username+",  Password fail"
		else:
			showH1 = "Not User : "+username
		user_data = 'not_user'	
		context = {	'user_data'  : user_data,
					'showH1' : showH1,
					'user_check' : user_check}
		return render(request, 'login_fail.html', context)

def profile(request, user_id):
	user_data = userData.objects.get(id=user_id)
	username = user_data.username
	lost_noitce_list = LostNoticeList.objects.filter(your_name=username)
	found_owner_list = FindOwnerList.objects.filter(your_name=username)

	
	context = {	'lost_noitce_list' : lost_noitce_list,
				'found_owner_list' : found_owner_list, 
				'user_data' : user_data }
	return render(request, 'profile_page.html', context)

def about(request):
	return render(request, 'about.html')

lostnotice/templates/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}

{% block content %} 

<h1>About Lose Notice</h1>

<section>
	เป็นเว็บที่มีไว้แปะประกาศของหาย หรือหาของเจอแล้วมาประกาศหาเจ้าของก็ได้เหมือนกัน  
 แต่ว่าตอนนี้ได้จำกัดบริเวณไว้ที่พระเจ้าเกล้าพระนครเหนือ
</section>
<br>
<section>
	ซึ่งผู้ที่จะทำการติดประกาศจะต้องทำการสมัครสมาชิกก่อนถึงจะประกาศได้
</section>
<br>
<section>
	พัฒนาโดย นายพุทธินันท์ เศษน้อย
</section>

 {% endblock %}

lostnotice/templates/add_new_found_owner.html
{% extends "base.html" %}
{% block title %}Add New Find Owner{% endblock %}

{% block content %} 

<h1>Add New Find Owner</h1>
Username : <B>{{user_data.username}}</B> <br>
E-mail : <B>{{user_data.email}}</B> <br><br>
        <form action="{% url 'save_new_found_owner' %}" method="POST">
        
    <div class="col-sm-4">
    Title : <input type="text" class="form-control" name="title" id="id_title" placeholder="Enter title" /></br>

    Name Item : <input type="text" class="form-control" name="name_item" id="id_name_item" placeholder="Enter name item" /></br>

    Detail :  <textarea class="form-control" name="detail" id="id_detail" placeholder="Enter Detail item lost" /></textarea></br>

    Time Found : <input type="text" class="form-control" name="time_found" id="id_time_lost" placeholder="Enter Time lost" /></br>

    Location : <input type="text" class="form-control" name="location_found" id="id_location_lost" placeholder="Enter Location lost" /></br>

    <input type="hidden" name="your_name" id="id_your_name" value={{user_data.username}} ></br>
    <input type="hidden" name="your_email" id="id_your_email" value={{user_data.email}} ></br>

    <input type="submit" value="Submit" class="btn btn-success">
            {% csrf_token %}
        </form>


 {% endblock %}

lostnotice/templates/add_new_lost_item.html
{% extends "base.html" %}
{% block title %}Add Lose Notice{% endblock %}

{% block content %} 

<h1>Add Lose Notice</h1>
Username : <B>{{user_data.username}}</B> <br>
E-mail : <B>{{user_data.email}}</B> <br><br>
        <form action="{% url 'save_new_item_lost' %}" method="POST">

      
    <div class="col-sm-4">
    Title : <input type="text" class="form-control" name="title" id="id_title" placeholder="Enter title" /></br> 
    
    Name Item : <input type="text" class="form-control" name="name_item" id="id_name_item" placeholder="Enter name item" /></br>
    
    Detail : <textarea class="form-control" name="detail" id="id_detail" placeholder="Enter Detail item lost" /></textarea></br>

    Time lost : <input type="text" class="form-control" name="time_lost" id="id_time_lost" placeholder="Enter Time lost" /></br>

    Location : <input type="text" class="form-control" name="location_lost" id="id_location_lost" placeholder="Enter Location lost" /></br>

    <input type="hidden" name="your_name" id="id_your_name" value={{user_data.username}} ></br>
    <input type="hidden" name="your_email" id="id_your_email" value={{user_data.email}} >
    
    <input type="submit" value="Submit" class="btn btn-success">
            {% csrf_token %}
        </form>


 {% endblock %}

lostnotice/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    {% block extra_head %}{% endblock %}

    <style>
    body {margin:0;}

    .topnav {
      overflow: hidden;
      background-color: #333;
    }

    .topnav a {
      float: left;
      display: block;
      color: #f2f2f2;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      font-size: 17px;
    }

    .topnav a:hover {
      background-color: #ddd;
      color: black;
    }

    .topnav a.active {
        background-color: #4CAF50;
        color: white;
    }
    </style>

</head>
<body><div class="topnav">
    <a class="active" href="{% url 'home' %}" >Home</a>
    {% block extra_topnav %}{% endblock %}
    {% if 'profile' in request.path or  'add_new' in request.path %}
        <a href="{% url 'profile'  user_data.id %}">Profile</a>
        <a href="{% url 'add_new_lost_item' user_data.id %}">Add new lost notice</a>
        <a href="{% url 'add_new_found_owner' user_data.id %}">Add new find owner</a>
    {% else %}        
        <a href="{% url 'login_page' %}">Login</a>
        <a href="{% url 'register_page' %}">Register</a>
    {% endif %}
    <a href="{% url 'about' %}">About</a>
</div>
<div class="container">
    
    {% block content %}
    {% endblock %}

    {% block extra_body %}
    {% endblock %}
</body>
</html>

lostnotice/templates/detail_found_owner.html
{% extends "base.html" %}
{% block title %}Detail Find Owner{% endblock %}

{% block content %} 

<h2>Detail Find Owner</h2>
<h1>{{found_owner_list.title}}</h1> <br>
<div id="name">Name item : {{found_owner_list.name_item}}</div> <br>
<div id="detail">Detail : {{found_owner_list.detail}}</div> <br>
<div id="time">Time lost : {{found_owner_list.time_found}}</div> <br>
<div id="Location">Location : {{found_owner_list.location_found}}</div> <br>
<div id="status">Find status : {{found_owner_list.found_owner}}</div> <br>
<div id="your_name">Username : {{found_owner_list.your_name}}</div> <br>
<div id="your_email">Email : {{found_owner_list.your_email}}</div> <br>


 {% endblock %}

lostnotice/templates/detail_lost_item.html
{% extends "base.html" %}
{% block title %}Detail Lost Notice{% endblock %}

{% block content %} 

<h2>Detail Lost Notice</h2>
<h1> {{lost_noitce_list.title}} </h1>

<div id="name_item">Name item : {{lost_noitce_list.name_item}}</div> <br>
<div id="detail">Detail : {{lost_noitce_list.detail}}</div> <br>
<div id="time_lost">Time lost : {{lost_noitce_list.time_lost}}</div> <br>
<div id="Location">Location : {{lost_noitce_list.location_lost}}</div> <br>
<div id="found_it">Found It : {{lost_noitce_list.found_it}}</div> <br>
<div id="your_name">Username : {{lost_noitce_list.your_name}}</div> <br>
<div id="your_email">Email : {{lost_noitce_list.your_email}}</div> <br>
<br>


 {% endblock %}

lostnotice/templates/homepage.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %} 

<br>
<h1>lost notice List</h1>
{% if lost_noitce_list %}
	{% for LostNoticeList in lost_noitce_list %}
		<tr><td><a href="{% url 'detail_lost_item' LostNoticeList.id %}" class="btn btn-link">{{ LostNoticeList.title }}</a></td></tr> <br>
	{% endfor %}

	{% if valueList.lPage > 1 %}		
			<a href="{% url 'home' valueList.leftLostPage valueList.fPage %}" class="btn btn-default" >to {{valueList.leftLostPage}} </a>
		{% endif %}
		now Page {{valueList.lPage}}

		{% if valueList.lPage < valueList.lost_last_page %} 
			<a href="{% url 'home' valueList.rightLostPage valueList.fPage %}" class="btn btn-default" >to {{valueList.rightLostPage}} </a>
	{% endif %}
{%else%}
	no lost notice list
{% endif %}

<br>
<h1>Find owner List</h1>
{% if found_owner_list %}
	{% for FindOwnerList in found_owner_list %}
		<tr><td><a href="{% url 'detail_found_owner' FindOwnerList.id %}" class="btn btn-link">{{ FindOwnerList.title }}</a></td></tr> <br>
	{% endfor %}

	{% if valueList.fPage > 1 %}		
		<a href="{% url 'home' valueList.lPage valueList.leftFoundPage %}" class="btn btn-default" >to {{valueList.leftFoundPage}} </a>
	{% endif %}
	now Page {{valueList.fPage}}

	{% if valueList.fPage < valueList.found_owner_page %} 
		<a href="{% url 'home' valueList.lPage valueList.rightFoundPage %}" class="btn btn-default" >to {{valueList.rightFoundPage}} </a>
	{% endif %}

{%else%}
no find owner list
{% endif %}


 {% endblock %}

lostnotice/templates/login_fail.html
{% extends "base.html" %}

{% block title %}Login Fail{% endblock %}

{% block content %} 

<h1>{{showH1}}</h1><br>
<a href="{% url 'login_page' %}" id="login_page" class="btn btn-warning">Login Again</a>
<b> | </b>
<a href="{% url 'register_page' %}" id="register_page" class="btn btn-default">Register</a>

{% endblock %}

lostnotice/templates/login_page.html
{% extends "base.html" %}
{% block title %} Login {% endblock %}

{% block content %} 

<h1>Login</h1>


<form action="{% url 'login_check' %}" method="POST">
	<br>
	<div class="col-sm-4">
	Username : <input type="text" class="form-control" name="username" id="id_name" placeholder="Enter Your name" /></br>

	Password : <input type="Password" class="form-control" name="password" id="id_password" placeholder="Enter Your Password" /></br>

	<input type="submit" value="Login" class="btn btn-success">
	{% csrf_token %}
        </form>


 {% endblock %}

lostnotice/templates/profile_page.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}

{% block content %} 

<h1>Profile</h1>
Username : <B>{{user_data.username}}</B> <br>
E-mail : <B>{{user_data.email}}</B> <br>
<br>
<b>lost notice list</b>
<table id="id_list_table">
</table>
{% if lost_noitce_list %}
	{% for LostNoticeList in lost_noitce_list %}
		<tr><td><a href="{% url 'detail_lost_item' LostNoticeList.id %}">{{ LostNoticeList.title }}</a></td></tr> <br>
	{% endfor %}
{%else%}
no lost notice list
{% endif %}

<br><br>
<b>find owner list</b>
<br>
{% if found_owner_list %}
	{% for FindOwnerList in found_owner_list %}
		<tr><td><a href="{% url 'detail_found_owner' FindOwnerList.id %}">{{ FindOwnerList.title }}</a></td></tr> <br>
	{% endfor %}
{%else%}
no find owner list
{% endif %}

 {% endblock %}

lostnotice/templates/register_check.html
{% extends "base.html" %}

{% block title %}

	{% if user_check %}
		Register Failed

	{% else %}
		Register Complete

	{% endif %}

{% endblock %}

{% block content %} 

{% if user_check %}
<h1>Register Failed</h1>
User : {{username}}<br>
<a href="{% url 'register_page' %}" id="register_page" class="btn btn-warning">Register Again</a>

{% else %}
<h1>Register Complete</h1>
User : {{username}}<br><br>
<a href="{% url 'login_page' %}" id="login_page" class="btn btn-success">Login</a> 
{% endif %}

{% endblock %}

lostnotice/templates/register_page.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}

{% block content %} 

<h1>Register</h1>


<form action="{% url 'register_check' %}" method="POST">
    <div class="col-sm-4">
	Username : <input type="text" class="form-control" name="username" id="id_name" placeholder="Enter Your name" /></br>

	E-mail : <input type="text" class="form-control" name="email" id="id_email" placeholder="Enter Your E-mail" /></br>

	Password : <input type="Password" class="form-control" name="password" id="id_password" placeholder="Enter Your Password" /></br>

	<input type="submit" value="Register" class="btn btn-success">
	{% csrf_token %}
        </form>


 {% endblock %}